VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "SimpleTestOne"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'
' SimpleTestOne
'
Option Explicit

Public Sub TestOne()
    Assert.Say "What is this?'"
End Sub

Public Sub TestTwo()
    Assert.AreEqual 1, 2, "Are we equal?"
End Sub
