VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "FilterList"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'    CopyRight (c) 2006 Kelly Ethridge
'
'    This file is part of SimplyVBUnitLib.
'
'    SimplyVBUnitLib is free software; you can redistribute it and/or modify
'    it under the terms of the GNU Library General Public License as published by
'    the Free Software Foundation; either version 2.1 of the License, or
'    (at your option) any later version.
'
'    SimplyVBUnitLib is distributed in the hope that it will be useful,
'    but WITHOUT ANY WARRANTY; without even the implied warranty of
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
'    GNU Library General Public License for more details.
'
'    You should have received a copy of the GNU Library General Public License
'    along with Foobar; if not, write to the Free Software
'    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
'
'    Module: FilterList
'

Option Explicit

Private mFilters As New Collection


Friend Sub Add(ByVal Filter As ITestFilter)
    If Not Filter Is Nothing Then
        Call mFilters.Add(Filter, CStr(ObjPtr(Filter)))
    End If
End Sub

Friend Sub Remove(ByVal Filter As ITestFilter)
    If Not Filter Is Nothing Then
        Call mFilters.Remove(CStr(ObjPtr(Filter)))
    End If
End Sub

Friend Function Include(ByVal Test As ITest) As Boolean
    Dim Filter As ITestFilter
    For Each Filter In mFilters
        If Not Filter.Include(Test) Then
            Exit Function
        End If
    Next Filter
    
    Include = True
End Function

Public Function NewEnum() As IUnknown
Attribute NewEnum.VB_UserMemId = -4
Attribute NewEnum.VB_MemberFlags = "40"
    Set NewEnum = mFilters.[_NewEnum]
End Function
